server:
  port: 8080

spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/product-recommend?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  # 配置jackson的时间格式
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
  session:
    timeout: 86400
  # 允许循环依赖
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  # 配置mybatis-plus的日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自定义图片上传路径
product:
  recommend:
    path:
      domain: http://localhost:8080
      address: D:\idea\project\product-recommend\src\main\resources\images
      user-prefix: /user/get/avatar/
      product-prefix: /product/get/image/